-- 2022-01 월의 도서판매 데이터를 기준으로 저자 별, 카테고리 별 매출 액 
 
WITH BOOK_SALE_TOT AS (
    SELECT 
        SAL.BOOK_ID,
        BO.CATEGORY,
        BO.AUTHOR_ID,
        BO.PRICE * SUM(SAL.SALES) AS BOOK_SALES
        
    FROM BOOK_SALES SAL
    JOIN BOOK BO ON SAL.BOOK_ID = BO.BOOK_ID
    WHERE SAL.SALES_DATE LIKE "2022-01%"
    GROUP BY SAL.BOOK_ID
)

SELECT
    AU.AUTHOR_ID, 
    AU.AUTHOR_NAME, 
    BOT.CATEGORY,
    SUM(BOT.BOOK_SALES) AS TOTAL_SALES
FROM BOOK_SALE_TOT BOT
JOIN AUTHOR AU ON BOT.AUTHOR_ID = AU.AUTHOR_ID
GROUP BY AU.AUTHOR_ID,  BOT.CATEGORY
ORDER BY AU.AUTHOR_ID,  BOT.CATEGORY DESC ;