
SELECT ID, FISH_NAME, LENGTH
FROM
    (
    SELECT 
        I.*,
        ROW_NUMBER() OVER (PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) as rn ,
        N.FISH_NAME
    FROM FISH_INFO I
    JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    ) as t
WHERE 
    rn = 1
ORDER BY ID;