WITH RENTAL_WITH_DURATION AS (
    SELECT 
        H.HISTORY_ID, 
        H.CAR_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAYS,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE 
        C.CAR_TYPE = '트럭'
),

RENTAL_WITH_DISCOUNT AS (
    SELECT 
        R.HISTORY_ID,
        R.DAILY_FEE,
        R.RENTAL_DAYS,
        IFNULL(D.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM 
        RENTAL_WITH_DURATION R
        LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON R.CAR_TYPE = D.CAR_TYPE AND R.DURATION_TYPE = D.DURATION_TYPE
)

SELECT 
    HISTORY_ID,
    ROUND(DAILY_FEE * RENTAL_DAYS * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM 
    RENTAL_WITH_DISCOUNT
ORDER BY 
    FEE DESC, HISTORY_ID DESC;
