--  종류가 '세단' 또는 'SUV' 인 자동차
--  2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
--  30일간의 대여 금액이 50만원 이상 200만원 미만

WITH RENT_IMP AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT (
        END_DATE < '2022-11-01' 
        OR START_DATE > '2022-11-30')),
    
    CAR_POS AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE 
        CAR_ID NOT IN (SELECT CAR_ID FROM RENT_IMP) AND CAR_TYPE IN ('세단', 'SUV')
    )
    
SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(30 * C.DAILY_FEE * ((100-D.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_POS C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE D.DURATION_TYPE = '30일 이상' 
    AND ROUND(30 * C.DAILY_FEE * ((100-D.DISCOUNT_RATE)/100)) BETWEEN 500000 AND 2000000 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC ;