WITH FRONT_CODE AS (
    SELECT SUM(CODE) 
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'    
)

SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM DEVELOPERS D
WHERE
    D.SKILL_CODE & (SELECT * FROM FRONT_CODE) > 0
ORDER BY D.ID    
    ; 