--  서울에 위치한 식당들의 식당 ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수

SELECT 
    INF.REST_ID,
    INF.REST_NAME,
    INF.FOOD_TYPE,
    INF.FAVORITES,
    INF.ADDRESS,
    ROUND(AVG(REV.REVIEW_SCORE), 2) AS SCORE
FROM 
    REST_INFO INF
JOIN
    REST_REVIEW REV ON INF.REST_ID = REV.REST_ID
WHERE
    INF.ADDRESS LIKE "서울%"
GROUP BY 
    INF.REST_ID
ORDER BY
    SCORE DESC, INF.FAVORITES DESC ;