

-- 총매출 조회

WITH ORDER_SUM AS (
    SELECT 
        PRODUCT_ID,
        SUM(AMOUNT) AS AMOUNT
    FROM 
        FOOD_ORDER
    WHERE
        PRODUCE_DATE LIKE "2022-05%" 
    GROUP BY 
        PRODUCT_ID
       
)

SELECT 
    O.PRODUCT_ID,
    P.PRODUCT_NAME,
    O.AMOUNT * P.PRICE AS TOTAL_SALES
FROM
    ORDER_SUM O
JOIN 
    FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID